/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAppCallRouteImport } from './routes/_authenticated/app.call'
import { Route as AuthenticatedAppChatRouteImport } from './routes/_authenticated/app.chat'
import { Route as AuthenticatedAppDashboardRouteImport } from './routes/_authenticated/app.dashboard'
import { Route as AuthenticatedAppLearnRouteImport } from './routes/_authenticated/app.learn'
import { Route as AuthenticatedAppMessageRouteImport } from './routes/_authenticated/app.message'
import { Route as AuthenticatedAppPaymentRouteImport } from './routes/_authenticated/app.payment'
import { Route as AuthenticatedAppWebsiteRouteImport } from './routes/_authenticated/app.website'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppCallRoute = AuthenticatedAppCallRouteImport.update({
  id: '/app/call',
  path: '/app/call',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppChatRoute = AuthenticatedAppChatRouteImport.update({
  id: '/app/chat',
  path: '/app/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppDashboardRoute =
  AuthenticatedAppDashboardRouteImport.update({
    id: '/app/dashboard',
    path: '/app/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppLearnRoute = AuthenticatedAppLearnRouteImport.update({
  id: '/app/learn',
  path: '/app/learn',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppMessageRoute = AuthenticatedAppMessageRouteImport.update({
  id: '/app/message',
  path: '/app/message',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppPaymentRoute = AuthenticatedAppPaymentRouteImport.update({
  id: '/app/payment',
  path: '/app/payment',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppWebsiteRoute = AuthenticatedAppWebsiteRouteImport.update({
  id: '/app/website',
  path: '/app/website',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/call': typeof AuthenticatedAppCallRoute
  '/app/chat': typeof AuthenticatedAppChatRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/learn': typeof AuthenticatedAppLearnRoute
  '/app/message': typeof AuthenticatedAppMessageRoute
  '/app/payment': typeof AuthenticatedAppPaymentRoute
  '/app/website': typeof AuthenticatedAppWebsiteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/call': typeof AuthenticatedAppCallRoute
  '/app/chat': typeof AuthenticatedAppChatRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/learn': typeof AuthenticatedAppLearnRoute
  '/app/message': typeof AuthenticatedAppMessageRoute
  '/app/payment': typeof AuthenticatedAppPaymentRoute
  '/app/website': typeof AuthenticatedAppWebsiteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app/call': typeof AuthenticatedAppCallRoute
  '/_authenticated/app/chat': typeof AuthenticatedAppChatRoute
  '/_authenticated/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/_authenticated/app/learn': typeof AuthenticatedAppLearnRoute
  '/_authenticated/app/message': typeof AuthenticatedAppMessageRoute
  '/_authenticated/app/payment': typeof AuthenticatedAppPaymentRoute
  '/_authenticated/app/website': typeof AuthenticatedAppWebsiteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app/call'
    | '/app/chat'
    | '/app/dashboard'
    | '/app/learn'
    | '/app/message'
    | '/app/payment'
    | '/app/website'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/call'
    | '/app/chat'
    | '/app/dashboard'
    | '/app/learn'
    | '/app/message'
    | '/app/payment'
    | '/app/website'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app/call'
    | '/_authenticated/app/chat'
    | '/_authenticated/app/dashboard'
    | '/_authenticated/app/learn'
    | '/_authenticated/app/message'
    | '/_authenticated/app/payment'
    | '/_authenticated/app/website'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/call': {
      id: '/_authenticated/app/call'
      path: '/app/call'
      fullPath: '/app/call'
      preLoaderRoute: typeof AuthenticatedAppCallRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/chat': {
      id: '/_authenticated/app/chat'
      path: '/app/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AuthenticatedAppChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/dashboard': {
      id: '/_authenticated/app/dashboard'
      path: '/app/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/learn': {
      id: '/_authenticated/app/learn'
      path: '/app/learn'
      fullPath: '/app/learn'
      preLoaderRoute: typeof AuthenticatedAppLearnRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/message': {
      id: '/_authenticated/app/message'
      path: '/app/message'
      fullPath: '/app/message'
      preLoaderRoute: typeof AuthenticatedAppMessageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/payment': {
      id: '/_authenticated/app/payment'
      path: '/app/payment'
      fullPath: '/app/payment'
      preLoaderRoute: typeof AuthenticatedAppPaymentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/website': {
      id: '/_authenticated/app/website'
      path: '/app/website'
      fullPath: '/app/website'
      preLoaderRoute: typeof AuthenticatedAppWebsiteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppCallRoute: typeof AuthenticatedAppCallRoute
  AuthenticatedAppChatRoute: typeof AuthenticatedAppChatRoute
  AuthenticatedAppDashboardRoute: typeof AuthenticatedAppDashboardRoute
  AuthenticatedAppLearnRoute: typeof AuthenticatedAppLearnRoute
  AuthenticatedAppMessageRoute: typeof AuthenticatedAppMessageRoute
  AuthenticatedAppPaymentRoute: typeof AuthenticatedAppPaymentRoute
  AuthenticatedAppWebsiteRoute: typeof AuthenticatedAppWebsiteRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppCallRoute: AuthenticatedAppCallRoute,
  AuthenticatedAppChatRoute: AuthenticatedAppChatRoute,
  AuthenticatedAppDashboardRoute: AuthenticatedAppDashboardRoute,
  AuthenticatedAppLearnRoute: AuthenticatedAppLearnRoute,
  AuthenticatedAppMessageRoute: AuthenticatedAppMessageRoute,
  AuthenticatedAppPaymentRoute: AuthenticatedAppPaymentRoute,
  AuthenticatedAppWebsiteRoute: AuthenticatedAppWebsiteRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
