/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAppDashboardRouteImport } from './routes/_authenticated/app.dashboard'
import { Route as AuthenticatedAppMessageRouteImport } from './routes/_authenticated/app.message'
import { Route as AuthenticatedAppWebsiteRouteImport } from './routes/_authenticated/app.website'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppDashboardRoute =
  AuthenticatedAppDashboardRouteImport.update({
    id: '/app/dashboard',
    path: '/app/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppMessageRoute = AuthenticatedAppMessageRouteImport.update({
  id: '/app/message',
  path: '/app/message',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppWebsiteRoute = AuthenticatedAppWebsiteRouteImport.update({
  id: '/app/website',
  path: '/app/website',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/message': typeof AuthenticatedAppMessageRoute
  '/app/website': typeof AuthenticatedAppWebsiteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/message': typeof AuthenticatedAppMessageRoute
  '/app/website': typeof AuthenticatedAppWebsiteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/_authenticated/app/message': typeof AuthenticatedAppMessageRoute
  '/_authenticated/app/website': typeof AuthenticatedAppWebsiteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/app/dashboard' | '/app/message' | '/app/website'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/app/dashboard' | '/app/message' | '/app/website'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app/dashboard'
    | '/_authenticated/app/message'
    | '/_authenticated/app/website'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/dashboard': {
      id: '/_authenticated/app/dashboard'
      path: '/app/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/message': {
      id: '/_authenticated/app/message'
      path: '/app/message'
      fullPath: '/app/message'
      preLoaderRoute: typeof AuthenticatedAppMessageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/website': {
      id: '/_authenticated/app/website'
      path: '/app/website'
      fullPath: '/app/website'
      preLoaderRoute: typeof AuthenticatedAppWebsiteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppDashboardRoute: typeof AuthenticatedAppDashboardRoute
  AuthenticatedAppMessageRoute: typeof AuthenticatedAppMessageRoute
  AuthenticatedAppWebsiteRoute: typeof AuthenticatedAppWebsiteRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppDashboardRoute: AuthenticatedAppDashboardRoute,
  AuthenticatedAppMessageRoute: AuthenticatedAppMessageRoute,
  AuthenticatedAppWebsiteRoute: AuthenticatedAppWebsiteRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
